# Generated by Django 4.2 on 2025-12-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_mobileno', models.CharField(max_length=15)),
                ('customer_password', models.CharField(max_length=128)),
                ('customer_profile_pic', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('customer_username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
