# Generated by Django 3.2 on 2026-02-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0003_auto_20260129_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregister',
            name='nickname',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customerregister',
            name='school_name',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
