# Generated by Django 4.2 on 2025-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_mobileno', models.CharField(max_length=15)),
                ('admin_password', models.CharField(max_length=128)),
                ('admin_profile_pic', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('admin_username', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
