# Generated by Django 3.2 on 2026-01-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=255)),
                ('series_director', models.CharField(default='Unknown', max_length=255)),
                ('series_banner', models.ImageField(upload_to='webseries_banners/')),
                ('total_seasons', models.IntegerField(default=1)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.genre')),
                ('series_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.language')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=100)),
                ('season_order', models.IntegerField()),
                ('season_release_date', models.DateField(blank=True, null=True)),
                ('season_banner', models.ImageField(blank=True, null=True, upload_to='season_banners/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons_list', to='admin_panel.webseries')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_director', models.CharField(max_length=255)),
                ('movie_release_date', models.DateField()),
                ('movie_banner', models.ImageField(upload_to='movie_banners/')),
                ('movie_duration', models.CharField(max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_video_url', models.URLField()),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.genre')),
                ('movie_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.language')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('episode_release_date', models.DateField(blank=True, null=True)),
                ('episode_banner', models.ImageField(blank=True, null=True, upload_to='episode_banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_episodes', to='admin_panel.season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='admin_panel.webseries')),
            ],
        ),
    ]
