# Generated by Django 3.2 on 2026-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_episode_genre_language_movie_season_webseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('category_name', 'genre_name')},
        ),
    ]
